name: convert_rai
description: A simple Thai land unit converter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.5.1+12

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.14.3
  intl: any
  flutter_riverpod: ^2.1.3
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  fonts:
    - family: MontserratAlternates
      fonts:
        - asset: fonts/MontserratAlternates-Regular.ttf
    - family: Prompt
      fonts:
        - asset: fonts/Prompt-Regular.ttf
  uses-material-design: true
  generate: true
  assets:
  - assets/images/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
