name: convert_rai
description: A simple Thai land unit converter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.11.0
  intl: ^0.17.0
  pattern_formatter: ^2.0.0
  google_mobile_ads: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: MontserratAlternates
      fonts:
        - asset: fonts/MontserratAlternates-Regular.ttf
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
