default_platform(:ios)

platform :ios do
  private_lane :asc_api_key do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: ENV["APP_STORE_CONNECT_KEY_FILEPATH"]
    )
  end

  desc "Fetch or generate the App Store signing certificate and provisioning profile"
  lane :certs do
    match(type: "appstore", readonly: is_ci, api_key: asc_api_key)
  end

  desc "Build the app and publish it to the App Store"
  lane :release do
    api_key = asc_api_key

    match(type: "appstore", readonly: is_ci, api_key: api_key)

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Runner.xcodeproj",
      code_sign_identity: "Apple Distribution",
      bundle_identifier: "dev.khanin.convertrai-ios",
      profile_name: lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]["dev.khanin.convertrai-ios"],
      team_id: "2LX246B32M"
    )

    new_build_number = app_store_build_number(
      api_key: api_key,
      live: false
    ) + 1

    sh("cd .. && flutter build ios --release --no-codesign --build-number=#{new_build_number}")

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )

    upload_to_app_store(
      api_key: api_key,
      submit_for_review: true,
      automatic_release: true,
      force: true,
      skip_screenshots: true
    )
  end
end
